import type { CalibrationItem } from '../types';

// Curated, verifiable, timeless true/false statements. A mix of true and false
// across categories and difficulty. Honesty rule: if a value is uncertain, it
// was dropped rather than guessed. `answer` is whether the statement is TRUE.

export const calibrationFacts: CalibrationItem[] = [
  // ── Geography ──────────────────────────────────────────────────────────
  { id: 'geo-001', statement: 'The Nile is the longest river in Africa.', answer: true, category: 'Geography', sourceHint: 'River lengths' },
  { id: 'geo-002', statement: 'Australia is both a country and a continent.', answer: true, category: 'Geography', sourceHint: 'Continents' },
  { id: 'geo-003', statement: 'Mount Everest is located in the Andes.', answer: false, category: 'Geography', sourceHint: 'It is in the Himalayas' },
  { id: 'geo-004', statement: 'Russia spans more time zones than any other country.', answer: true, category: 'Geography', sourceHint: 'Time zones' },
  { id: 'geo-005', statement: 'The capital of Canada is Toronto.', answer: false, category: 'Geography', sourceHint: 'It is Ottawa' },
  { id: 'geo-006', statement: 'The Sahara is the largest hot desert in the world.', answer: true, category: 'Geography', sourceHint: 'Deserts' },
  { id: 'geo-007', statement: 'Greenland is the largest island in the world.', answer: true, category: 'Geography', sourceHint: 'Islands (Australia counts as a continent)' },
  { id: 'geo-008', statement: 'Lake Baikal is the deepest lake on Earth.', answer: true, category: 'Geography', sourceHint: 'Lakes' },
  { id: 'geo-009', statement: 'The Amazon River flows into the Pacific Ocean.', answer: false, category: 'Geography', sourceHint: 'It flows into the Atlantic' },
  { id: 'geo-010', statement: 'Istanbul straddles two continents.', answer: true, category: 'Geography', sourceHint: 'Europe and Asia' },
  { id: 'geo-011', statement: 'The Dead Sea is the lowest exposed land elevation on Earth.', answer: true, category: 'Geography', sourceHint: 'Shoreline below sea level' },
  { id: 'geo-012', statement: 'Africa is the second-largest continent by area.', answer: true, category: 'Geography', sourceHint: 'After Asia' },
  { id: 'geo-013', statement: 'The capital of Australia is Sydney.', answer: false, category: 'Geography', sourceHint: 'It is Canberra' },
  { id: 'geo-014', statement: 'Vatican City is the smallest country in the world by area.', answer: true, category: 'Geography', sourceHint: 'Sovereign states' },
  { id: 'geo-015', statement: 'The Great Barrier Reef lies off the coast of Brazil.', answer: false, category: 'Geography', sourceHint: 'It is off Australia' },
  { id: 'geo-016', statement: 'Chile is the longest country in the world from north to south.', answer: true, category: 'Geography', sourceHint: 'Country shapes' },
  { id: 'geo-017', statement: 'The Equator passes through Brazil.', answer: true, category: 'Geography', sourceHint: 'Equator crossings' },
  { id: 'geo-018', statement: 'Iceland sits on the Mid-Atlantic Ridge.', answer: true, category: 'Geography', sourceHint: 'Plate boundaries' },
  { id: 'geo-019', statement: 'The capital of Spain is Barcelona.', answer: false, category: 'Geography', sourceHint: 'It is Madrid' },
  { id: 'geo-020', statement: 'New Zealand lies entirely in the Southern Hemisphere.', answer: true, category: 'Geography', sourceHint: 'Hemispheres' },
  { id: 'geo-021', statement: 'The Ural Mountains traditionally divide Europe and Asia.', answer: true, category: 'Geography', sourceHint: 'Continental divide' },
  { id: 'geo-022', statement: 'Mongolia is landlocked.', answer: true, category: 'Geography', sourceHint: 'No coastline' },
  { id: 'geo-023', statement: 'The capital of Egypt is Cairo.', answer: true, category: 'Geography', sourceHint: 'Capitals' },
  { id: 'geo-024', statement: 'Japan is made up of more than a thousand islands.', answer: true, category: 'Geography', sourceHint: 'Japanese archipelago' },
  { id: 'geo-025', statement: 'The Panama Canal connects the Atlantic and Pacific oceans.', answer: true, category: 'Geography', sourceHint: 'Canals' },
  { id: 'geo-026', statement: 'Kilimanjaro is the highest mountain in Africa.', answer: true, category: 'Geography', sourceHint: 'African peaks' },
  { id: 'geo-027', statement: 'The capital of Brazil is Rio de Janeiro.', answer: false, category: 'Geography', sourceHint: 'It is Brasília' },
  { id: 'geo-028', statement: 'Switzerland borders Germany, France, Italy, and Austria.', answer: true, category: 'Geography', sourceHint: 'Borders (also Liechtenstein)' },
  { id: 'geo-029', statement: 'The Caspian Sea is the largest enclosed inland body of water on Earth.', answer: true, category: 'Geography', sourceHint: 'Inland seas' },
  { id: 'geo-030', statement: 'Antarctica has no permanent human population.', answer: true, category: 'Geography', sourceHint: 'Only rotating researchers' },

  // ── Science & Physics ─────────────────────────────────────────────────
  { id: 'sci-001', statement: 'Water is composed of hydrogen and oxygen.', answer: true, category: 'Science', sourceHint: 'H2O' },
  { id: 'sci-002', statement: 'Sound travels faster than light.', answer: false, category: 'Science', sourceHint: 'Light is far faster' },
  { id: 'sci-003', statement: 'The chemical symbol for gold is Au.', answer: true, category: 'Science', sourceHint: 'Periodic table' },
  { id: 'sci-004', statement: 'The chemical symbol for sodium is So.', answer: false, category: 'Science', sourceHint: 'It is Na' },
  { id: 'sci-005', statement: 'Helium is lighter than air.', answer: true, category: 'Science', sourceHint: 'Buoyancy' },
  { id: 'sci-006', statement: 'At sea level, pure water boils at 100 °C.', answer: true, category: 'Science', sourceHint: 'Standard pressure' },
  { id: 'sci-007', statement: 'Diamond is a form of carbon.', answer: true, category: 'Science', sourceHint: 'Allotropes' },
  { id: 'sci-008', statement: 'Electrons carry a positive electric charge.', answer: false, category: 'Science', sourceHint: 'They are negative' },
  { id: 'sci-009', statement: 'The speed of light in a vacuum is roughly 300,000 km per second.', answer: true, category: 'Science', sourceHint: '~299,792 km/s' },
  { id: 'sci-010', statement: 'Absolute zero is approximately −273 °C.', answer: true, category: 'Science', sourceHint: '0 kelvin' },
  { id: 'sci-011', statement: 'Rust forms when iron reacts with oxygen.', answer: true, category: 'Science', sourceHint: 'Oxidation' },
  { id: 'sci-012', statement: 'Glass is a metal.', answer: false, category: 'Science', sourceHint: 'It is an amorphous solid' },
  { id: 'sci-013', statement: 'The most abundant gas in Earth’s atmosphere is nitrogen.', answer: true, category: 'Science', sourceHint: '~78%' },
  { id: 'sci-014', statement: 'Lightning is hotter than the surface of the Sun.', answer: true, category: 'Science', sourceHint: 'Lightning channel ~30,000 K' },
  { id: 'sci-015', statement: 'Mercury is the only metal that is liquid at room temperature.', answer: true, category: 'Science', sourceHint: 'Room-temp liquids' },
  { id: 'sci-016', statement: 'Energy can be created from nothing.', answer: false, category: 'Science', sourceHint: 'Conservation of energy' },
  { id: 'sci-017', statement: 'The pH of a neutral solution is 7.', answer: true, category: 'Science', sourceHint: 'pH scale' },
  { id: 'sci-018', statement: 'Ultraviolet light has a shorter wavelength than infrared light.', answer: true, category: 'Science', sourceHint: 'Spectrum' },
  { id: 'sci-019', statement: 'Oxygen makes up about half of Earth’s atmosphere.', answer: false, category: 'Science', sourceHint: 'It is ~21%' },
  { id: 'sci-020', statement: 'A magnet has both a north and a south pole.', answer: true, category: 'Science', sourceHint: 'Dipoles' },
  { id: 'sci-021', statement: 'The element with atomic number 1 is hydrogen.', answer: true, category: 'Science', sourceHint: 'Periodic table' },
  { id: 'sci-022', statement: 'Salt dissolved in water lowers its freezing point.', answer: true, category: 'Science', sourceHint: 'Freezing-point depression' },
  { id: 'sci-023', statement: 'Light from the Sun takes about 8 minutes to reach Earth.', answer: true, category: 'Science', sourceHint: '~8.3 minutes' },
  { id: 'sci-024', statement: 'Graphite can conduct electricity.', answer: true, category: 'Science', sourceHint: 'Carbon allotrope' },
  { id: 'sci-025', statement: 'A year on Venus is shorter than a day on Venus.', answer: true, category: 'Science', sourceHint: 'Slow rotation' },

  // ── Astronomy ──────────────────────────────────────────────────────────
  { id: 'ast-001', statement: 'The Sun is a star.', answer: true, category: 'Astronomy', sourceHint: 'Stellar classification' },
  { id: 'ast-002', statement: 'Jupiter is the largest planet in the Solar System.', answer: true, category: 'Astronomy', sourceHint: 'Planet sizes' },
  { id: 'ast-003', statement: 'Mars is known as the Red Planet.', answer: true, category: 'Astronomy', sourceHint: 'Iron oxide surface' },
  { id: 'ast-004', statement: 'The Moon produces its own light.', answer: false, category: 'Astronomy', sourceHint: 'It reflects sunlight' },
  { id: 'ast-005', statement: 'Saturn is the planet famous for its prominent rings.', answer: true, category: 'Astronomy', sourceHint: 'Ring systems' },
  { id: 'ast-006', statement: 'Pluto is currently classified as a dwarf planet.', answer: true, category: 'Astronomy', sourceHint: 'IAU 2006' },
  { id: 'ast-007', statement: 'Mercury is the closest planet to the Sun.', answer: true, category: 'Astronomy', sourceHint: 'Orbital order' },
  { id: 'ast-008', statement: 'A light-year measures time, not distance.', answer: false, category: 'Astronomy', sourceHint: 'It is a distance' },
  { id: 'ast-009', statement: 'The Milky Way is the galaxy that contains our Solar System.', answer: true, category: 'Astronomy', sourceHint: 'Home galaxy' },
  { id: 'ast-010', statement: 'Venus is the hottest planet in the Solar System.', answer: true, category: 'Astronomy', sourceHint: 'Runaway greenhouse' },
  { id: 'ast-011', statement: 'Neptune is the eighth planet from the Sun.', answer: true, category: 'Astronomy', sourceHint: 'Orbital order' },
  { id: 'ast-012', statement: 'The Sun is mostly made of iron.', answer: false, category: 'Astronomy', sourceHint: 'Mostly hydrogen and helium' },
  { id: 'ast-013', statement: 'Halley’s Comet is visible from Earth roughly every 76 years.', answer: true, category: 'Astronomy', sourceHint: 'Orbital period' },
  { id: 'ast-014', statement: 'Earth has more than one natural moon.', answer: false, category: 'Astronomy', sourceHint: 'Only one' },
  { id: 'ast-015', statement: 'The asteroid belt lies between Mars and Jupiter.', answer: true, category: 'Astronomy', sourceHint: 'Solar System layout' },

  // ── Biology ────────────────────────────────────────────────────────────
  { id: 'bio-001', statement: 'The human body has 206 bones in adulthood.', answer: true, category: 'Biology', sourceHint: 'Adult skeleton' },
  { id: 'bio-002', statement: 'Humans have three lungs.', answer: false, category: 'Biology', sourceHint: 'Two lungs' },
  { id: 'bio-003', statement: 'DNA carries genetic information.', answer: true, category: 'Biology', sourceHint: 'Molecular biology' },
  { id: 'bio-004', statement: 'Spiders are insects.', answer: false, category: 'Biology', sourceHint: 'They are arachnids' },
  { id: 'bio-005', statement: 'The heart is a muscle.', answer: true, category: 'Biology', sourceHint: 'Cardiac muscle' },
  { id: 'bio-006', statement: 'Bats are mammals.', answer: true, category: 'Biology', sourceHint: 'Class Mammalia' },
  { id: 'bio-007', statement: 'Plants release oxygen during photosynthesis.', answer: true, category: 'Biology', sourceHint: 'Photosynthesis' },
  { id: 'bio-008', statement: 'A tomato is botanically a fruit.', answer: true, category: 'Biology', sourceHint: 'Botany' },
  { id: 'bio-009', statement: 'Human blood is blue inside the body.', answer: false, category: 'Biology', sourceHint: 'It is always red' },
  { id: 'bio-010', statement: 'Sharks are fish.', answer: true, category: 'Biology', sourceHint: 'Cartilaginous fish' },
  { id: 'bio-011', statement: 'Whales are fish.', answer: false, category: 'Biology', sourceHint: 'They are mammals' },
  { id: 'bio-012', statement: 'The largest organ of the human body is the skin.', answer: true, category: 'Biology', sourceHint: 'Integumentary system' },
  { id: 'bio-013', statement: 'Octopuses have three hearts.', answer: true, category: 'Biology', sourceHint: 'Cephalopod anatomy' },
  { id: 'bio-014', statement: 'Penguins can fly.', answer: false, category: 'Biology', sourceHint: 'Flightless birds' },
  { id: 'bio-015', statement: 'Honey is produced by bees.', answer: true, category: 'Biology', sourceHint: 'Apiculture' },
  { id: 'bio-016', statement: 'The adult human heart typically beats around 60–100 times per minute at rest.', answer: true, category: 'Biology', sourceHint: 'Resting heart rate' },
  { id: 'bio-017', statement: 'Bananas grow on trees.', answer: false, category: 'Biology', sourceHint: 'Banana plants are giant herbs' },
  { id: 'bio-018', statement: 'Humans share a large fraction of their DNA with chimpanzees.', answer: true, category: 'Biology', sourceHint: 'Comparative genomics' },
  { id: 'bio-019', statement: 'A frog is an amphibian.', answer: true, category: 'Biology', sourceHint: 'Class Amphibia' },
  { id: 'bio-020', statement: 'Carrots were originally mostly orange.', answer: false, category: 'Biology', sourceHint: 'Early cultivars were purple/yellow' },
  { id: 'bio-021', statement: 'Mushrooms belong to the plant kingdom.', answer: false, category: 'Biology', sourceHint: 'They are fungi' },
  { id: 'bio-022', statement: 'Adult humans have 32 teeth including wisdom teeth.', answer: true, category: 'Biology', sourceHint: 'Dental anatomy' },
  { id: 'bio-023', statement: 'Snakes have no legs.', answer: true, category: 'Biology', sourceHint: 'Limbless reptiles' },
  { id: 'bio-024', statement: 'The cheetah is the fastest land animal.', answer: true, category: 'Biology', sourceHint: 'Sprint speed' },
  { id: 'bio-025', statement: 'Cows have four-chambered stomachs.', answer: true, category: 'Biology', sourceHint: 'Ruminant digestion' },

  // ── History ────────────────────────────────────────────────────────────
  { id: 'his-001', statement: 'World War II ended in 1945.', answer: true, category: 'History', sourceHint: 'Surrenders of 1945' },
  { id: 'his-002', statement: 'The Great Wall of China is in Egypt.', answer: false, category: 'History', sourceHint: 'It is in China' },
  { id: 'his-003', statement: 'The first human to walk on the Moon was Neil Armstrong.', answer: true, category: 'History', sourceHint: 'Apollo 11, 1969' },
  { id: 'his-004', statement: 'The Roman Empire predates the Egyptian pyramids of Giza.', answer: false, category: 'History', sourceHint: 'Pyramids are far older' },
  { id: 'his-005', statement: 'The printing press in Europe is credited to Johannes Gutenberg.', answer: true, category: 'History', sourceHint: '15th century' },
  { id: 'his-006', statement: 'The Berlin Wall fell in 1989.', answer: true, category: 'History', sourceHint: 'November 1989' },
  { id: 'his-007', statement: 'Ancient Egypt built the Great Pyramid of Giza.', answer: true, category: 'History', sourceHint: 'Old Kingdom' },
  { id: 'his-008', statement: 'The Titanic sank on its maiden voyage.', answer: true, category: 'History', sourceHint: '1912' },
  { id: 'his-009', statement: 'The United States declared independence in 1776.', answer: true, category: 'History', sourceHint: 'Declaration of Independence' },
  { id: 'his-010', statement: 'Leonardo da Vinci painted the Mona Lisa.', answer: true, category: 'History', sourceHint: 'Renaissance art' },
  { id: 'his-011', statement: 'The French Revolution began in 1789.', answer: true, category: 'History', sourceHint: 'Storming of the Bastille' },
  { id: 'his-012', statement: 'The ancient Olympic Games were held in Greece.', answer: true, category: 'History', sourceHint: 'Olympia' },
  { id: 'his-013', statement: 'Napoleon Bonaparte was originally from Germany.', answer: false, category: 'History', sourceHint: 'He was from Corsica, France' },
  { id: 'his-014', statement: 'The Cold War was a direct, declared military war between two nations.', answer: false, category: 'History', sourceHint: 'It was a geopolitical tension' },
  { id: 'his-015', statement: 'The Wright brothers made the first powered airplane flight.', answer: true, category: 'History', sourceHint: '1903, Kitty Hawk' },
  { id: 'his-016', statement: 'The Magna Carta was signed in England.', answer: true, category: 'History', sourceHint: '1215' },
  { id: 'his-017', statement: 'Christopher Columbus reached the Americas in 1492.', answer: true, category: 'History', sourceHint: 'First voyage' },
  { id: 'his-018', statement: 'The Eiffel Tower was built for a World’s Fair.', answer: true, category: 'History', sourceHint: '1889 Exposition Universelle' },
  { id: 'his-019', statement: 'The Renaissance began in Italy.', answer: true, category: 'History', sourceHint: 'Florence and beyond' },
  { id: 'his-020', statement: 'Julius Caesar was a Roman leader.', answer: true, category: 'History', sourceHint: 'Roman Republic' },

  // ── Mathematics ────────────────────────────────────────────────────────
  { id: 'mat-001', statement: 'A prime number has exactly two distinct positive divisors.', answer: true, category: 'Mathematics', sourceHint: 'Definition of prime' },
  { id: 'mat-002', statement: 'The number 1 is a prime number.', answer: false, category: 'Mathematics', sourceHint: 'It has only one divisor' },
  { id: 'mat-003', statement: 'The sum of the interior angles of a triangle is 180 degrees.', answer: true, category: 'Mathematics', sourceHint: 'Euclidean geometry' },
  { id: 'mat-004', statement: 'Pi is exactly equal to 22/7.', answer: false, category: 'Mathematics', sourceHint: '22/7 is an approximation' },
  { id: 'mat-005', statement: 'Zero is an even number.', answer: true, category: 'Mathematics', sourceHint: 'Divisible by 2' },
  { id: 'mat-006', statement: 'The square root of 144 is 12.', answer: true, category: 'Mathematics', sourceHint: '12 × 12' },
  { id: 'mat-007', statement: 'A right angle measures 90 degrees.', answer: true, category: 'Mathematics', sourceHint: 'Angles' },
  { id: 'mat-008', statement: 'Every even number greater than 2 is prime.', answer: false, category: 'Mathematics', sourceHint: 'They are divisible by 2' },
  { id: 'mat-009', statement: 'A dozen equals twelve.', answer: true, category: 'Mathematics', sourceHint: 'Counting' },
  { id: 'mat-010', statement: 'The number pi is irrational.', answer: true, category: 'Mathematics', sourceHint: 'Proven irrational' },
  { id: 'mat-011', statement: 'Multiplying any number by zero gives zero.', answer: true, category: 'Mathematics', sourceHint: 'Zero property' },
  { id: 'mat-012', statement: '7 is a factor of 49.', answer: true, category: 'Mathematics', sourceHint: '7 × 7' },
  { id: 'mat-013', statement: 'The hypotenuse is the longest side of a right triangle.', answer: true, category: 'Mathematics', sourceHint: 'Opposite the right angle' },
  { id: 'mat-014', statement: 'A percentage cannot exceed 100.', answer: false, category: 'Mathematics', sourceHint: 'Percentages can exceed 100%' },
  { id: 'mat-015', statement: 'The factorial of 5 (5!) equals 120.', answer: true, category: 'Mathematics', sourceHint: '5×4×3×2×1' },

  // ── Language & Literature ─────────────────────────────────────────────
  { id: 'lan-001', statement: 'Shakespeare wrote the play “Hamlet”.', answer: true, category: 'Language', sourceHint: 'Elizabethan drama' },
  { id: 'lan-002', statement: 'The English alphabet has 26 letters.', answer: true, category: 'Language', sourceHint: 'Modern Latin alphabet' },
  { id: 'lan-003', statement: 'A noun is a word that describes an action.', answer: false, category: 'Language', sourceHint: 'That is a verb' },
  { id: 'lan-004', statement: 'Latin is the root of many Romance languages.', answer: true, category: 'Language', sourceHint: 'Spanish, French, Italian, etc.' },
  { id: 'lan-005', statement: 'A haiku traditionally has three lines.', answer: true, category: 'Language', sourceHint: '5-7-5 syllables' },
  { id: 'lan-006', statement: 'Mandarin Chinese has more native speakers than any other language.', answer: true, category: 'Language', sourceHint: 'Native-speaker counts' },
  { id: 'lan-007', statement: 'The word “bibliophile” means a lover of books.', answer: true, category: 'Language', sourceHint: 'Greek roots' },
  { id: 'lan-008', statement: 'An antonym is a word with the same meaning as another.', answer: false, category: 'Language', sourceHint: 'That is a synonym' },
  { id: 'lan-009', statement: 'Esperanto is a constructed language.', answer: true, category: 'Language', sourceHint: 'Invented by Zamenhof' },
  { id: 'lan-010', statement: 'The novel “War and Peace” was written by Leo Tolstoy.', answer: true, category: 'Language', sourceHint: 'Russian literature' },
  { id: 'lan-011', statement: 'A palindrome reads the same forwards and backwards.', answer: true, category: 'Language', sourceHint: 'e.g., “level”' },
  { id: 'lan-012', statement: 'The Greek letter that comes first in the alphabet is omega.', answer: false, category: 'Language', sourceHint: 'It is alpha' },
  { id: 'lan-013', statement: 'Braille is a writing system read by touch.', answer: true, category: 'Language', sourceHint: 'Tactile reading' },
  { id: 'lan-014', statement: 'Arabic is read right to left.', answer: true, category: 'Language', sourceHint: 'Script direction' },
  { id: 'lan-015', statement: 'A “lexicon” is another word for a vocabulary or dictionary.', answer: true, category: 'Language', sourceHint: 'Word stock' },

  // ── Everyday & Misc ────────────────────────────────────────────────────
  { id: 'msc-001', statement: 'A standard analog clock has 12 numbered hours.', answer: true, category: 'Everyday', sourceHint: 'Clock faces' },
  { id: 'msc-002', statement: 'There are 60 minutes in an hour.', answer: true, category: 'Everyday', sourceHint: 'Time units' },
  { id: 'msc-003', statement: 'A standard chessboard has 64 squares.', answer: true, category: 'Everyday', sourceHint: '8×8 grid' },
  { id: 'msc-004', statement: 'A leap year has 366 days.', answer: true, category: 'Everyday', sourceHint: 'Calendar' },
  { id: 'msc-005', statement: 'The freezing point of water at sea level is 0 °C.', answer: true, category: 'Everyday', sourceHint: 'Celsius scale' },
  { id: 'msc-006', statement: 'A standard six-sided die has its opposite faces summing to 7.', answer: true, category: 'Everyday', sourceHint: 'Dice convention' },
  { id: 'msc-007', statement: 'There are 52 cards in a standard deck (excluding jokers).', answer: true, category: 'Everyday', sourceHint: 'Playing cards' },
  { id: 'msc-008', statement: 'A week has eight days.', answer: false, category: 'Everyday', sourceHint: 'Seven days' },
  { id: 'msc-009', statement: 'The primary colors of light are red, green, and blue.', answer: true, category: 'Everyday', sourceHint: 'Additive color' },
  { id: 'msc-010', statement: 'A century is 100 years.', answer: true, category: 'Everyday', sourceHint: 'Time spans' },
  { id: 'msc-011', statement: 'The metric system is based on powers of ten.', answer: true, category: 'Everyday', sourceHint: 'Decimal units' },
  { id: 'msc-012', statement: 'A triangle has four sides.', answer: false, category: 'Everyday', sourceHint: 'It has three' },
  { id: 'msc-013', statement: 'Sound cannot travel through a vacuum.', answer: true, category: 'Everyday', sourceHint: 'Needs a medium' },
  { id: 'msc-014', statement: 'A kilometer is longer than a mile.', answer: false, category: 'Everyday', sourceHint: 'A mile is ~1.6 km' },
  { id: 'msc-015', statement: 'Roman numeral X represents ten.', answer: true, category: 'Everyday', sourceHint: 'Roman numerals' },

  // ── Geography (extended) ──────────────────────────────────────────────
  { id: 'geo-031', statement: 'The capital of Japan is Tokyo.', answer: true, category: 'Geography', sourceHint: 'Capitals' },
  { id: 'geo-032', statement: 'The Mississippi River is the longest river in North America by some measures.', answer: true, category: 'Geography', sourceHint: 'Missouri–Mississippi system' },
  { id: 'geo-033', statement: 'India is in the Southern Hemisphere.', answer: false, category: 'Geography', sourceHint: 'Mostly Northern Hemisphere' },
  { id: 'geo-034', statement: 'The Atlantic is the second-largest ocean.', answer: true, category: 'Geography', sourceHint: 'After the Pacific' },
  { id: 'geo-035', statement: 'Madagascar is an island nation off the coast of Africa.', answer: true, category: 'Geography', sourceHint: 'Indian Ocean' },
  { id: 'geo-036', statement: 'The capital of Italy is Rome.', answer: true, category: 'Geography', sourceHint: 'Capitals' },
  { id: 'geo-037', statement: 'The Andes are the longest continental mountain range in the world.', answer: true, category: 'Geography', sourceHint: 'South America' },
  { id: 'geo-038', statement: 'Norway is famous for its fjords.', answer: true, category: 'Geography', sourceHint: 'Glacial coastline' },
  { id: 'geo-039', statement: 'The capital of Germany is Munich.', answer: false, category: 'Geography', sourceHint: 'It is Berlin' },
  { id: 'geo-040', statement: 'The Gobi Desert is in Asia.', answer: true, category: 'Geography', sourceHint: 'Mongolia and China' },
  { id: 'geo-041', statement: 'Cuba is an island in the Caribbean.', answer: true, category: 'Geography', sourceHint: 'Greater Antilles' },
  { id: 'geo-042', statement: 'The Pacific Ocean is the largest ocean on Earth.', answer: true, category: 'Geography', sourceHint: 'Ocean basins' },
  { id: 'geo-043', statement: 'Portugal borders Spain.', answer: true, category: 'Geography', sourceHint: 'Iberian Peninsula' },
  { id: 'geo-044', statement: 'The capital of South Korea is Seoul.', answer: true, category: 'Geography', sourceHint: 'Capitals' },
  { id: 'geo-045', statement: 'The Thames runs through London.', answer: true, category: 'Geography', sourceHint: 'UK rivers' },
  { id: 'geo-046', statement: 'Bolivia has a coastline on the Pacific Ocean.', answer: false, category: 'Geography', sourceHint: 'It is landlocked' },
  { id: 'geo-047', statement: 'Hawaii is a group of volcanic islands.', answer: true, category: 'Geography', sourceHint: 'Volcanic archipelago' },
  { id: 'geo-048', statement: 'The Rhine flows through several European countries.', answer: true, category: 'Geography', sourceHint: 'Central Europe' },
  { id: 'geo-049', statement: 'Singapore is a city-state.', answer: true, category: 'Geography', sourceHint: 'Sovereign city-state' },
  { id: 'geo-050', statement: 'The capital of Argentina is Buenos Aires.', answer: true, category: 'Geography', sourceHint: 'Capitals' },

  // ── Science (extended) ────────────────────────────────────────────────
  { id: 'sci-026', statement: 'Photosynthesis occurs in chloroplasts.', answer: true, category: 'Science', sourceHint: 'Plant cells' },
  { id: 'sci-027', statement: 'Carbon dioxide is denser than oxygen.', answer: true, category: 'Science', sourceHint: 'Molar masses' },
  { id: 'sci-028', statement: 'Stainless steel is an alloy.', answer: true, category: 'Science', sourceHint: 'Iron, chromium, etc.' },
  { id: 'sci-029', statement: 'Sound travels faster in water than in air.', answer: true, category: 'Science', sourceHint: 'Medium density' },
  { id: 'sci-030', statement: 'The freezing and boiling points of water are the same temperature.', answer: false, category: 'Science', sourceHint: '0 °C vs 100 °C' },
  { id: 'sci-031', statement: 'An object in free fall accelerates due to gravity.', answer: true, category: 'Science', sourceHint: 'Newtonian mechanics' },
  { id: 'sci-032', statement: 'Copper is a good conductor of electricity.', answer: true, category: 'Science', sourceHint: 'Wiring' },
  { id: 'sci-033', statement: 'Ice is denser than liquid water.', answer: false, category: 'Science', sourceHint: 'Ice floats' },
  { id: 'sci-034', statement: 'A catalyst speeds up a chemical reaction without being consumed.', answer: true, category: 'Science', sourceHint: 'Catalysis' },
  { id: 'sci-035', statement: 'The smallest unit of an element that retains its properties is an atom.', answer: true, category: 'Science', sourceHint: 'Atomic theory' },
  { id: 'sci-036', statement: 'Helium is the second most abundant element in the universe.', answer: true, category: 'Science', sourceHint: 'After hydrogen' },
  { id: 'sci-037', statement: 'Magnets attract aluminum strongly.', answer: false, category: 'Science', sourceHint: 'Aluminum is not ferromagnetic' },
  { id: 'sci-038', statement: 'Thunder is caused by the rapid expansion of air heated by lightning.', answer: true, category: 'Science', sourceHint: 'Shock wave' },
  { id: 'sci-039', statement: 'A solar eclipse occurs when the Moon passes between the Earth and the Sun.', answer: true, category: 'Science', sourceHint: 'Eclipse geometry' },
  { id: 'sci-040', statement: 'Pure gold is harder than steel.', answer: false, category: 'Science', sourceHint: 'Gold is soft' },

  // ── History (extended) ────────────────────────────────────────────────
  { id: 'his-021', statement: 'The Colosseum is located in Rome.', answer: true, category: 'History', sourceHint: 'Ancient Rome' },
  { id: 'his-022', statement: 'The first modern Olympic Games were held in 1896.', answer: true, category: 'History', sourceHint: 'Athens' },
  { id: 'his-023', statement: 'Albert Einstein developed the theory of relativity.', answer: true, category: 'History', sourceHint: 'Physics history' },
  { id: 'his-024', statement: 'The Soviet Union launched the first artificial satellite, Sputnik.', answer: true, category: 'History', sourceHint: '1957' },
  { id: 'his-025', statement: 'The ancient city of Pompeii was buried by a volcanic eruption.', answer: true, category: 'History', sourceHint: 'Mount Vesuvius, 79 AD' },
  { id: 'his-026', statement: 'The Hundred Years’ War lasted exactly 100 years.', answer: false, category: 'History', sourceHint: 'It lasted 116 years' },
  { id: 'his-027', statement: 'Marie Curie won Nobel Prizes in two different sciences.', answer: true, category: 'History', sourceHint: 'Physics and Chemistry' },
  { id: 'his-028', statement: 'The Statue of Liberty was a gift from France to the United States.', answer: true, category: 'History', sourceHint: '1886' },
  { id: 'his-029', statement: 'The Industrial Revolution began in Britain.', answer: true, category: 'History', sourceHint: '18th century' },
  { id: 'his-030', statement: 'The Taj Mahal was built as a mausoleum.', answer: true, category: 'History', sourceHint: 'Mughal India' },

  // ── Biology (extended) ────────────────────────────────────────────────
  { id: 'bio-026', statement: 'Humans are warm-blooded.', answer: true, category: 'Biology', sourceHint: 'Endothermy' },
  { id: 'bio-027', statement: 'Reptiles are warm-blooded.', answer: false, category: 'Biology', sourceHint: 'They are ectothermic' },
  { id: 'bio-028', statement: 'The pancreas produces insulin.', answer: true, category: 'Biology', sourceHint: 'Endocrine function' },
  { id: 'bio-029', statement: 'Trees take in carbon dioxide and release oxygen.', answer: true, category: 'Biology', sourceHint: 'Photosynthesis' },
  { id: 'bio-030', statement: 'A caterpillar transforms into a butterfly.', answer: true, category: 'Biology', sourceHint: 'Metamorphosis' },
  { id: 'bio-031', statement: 'Jellyfish have brains.', answer: false, category: 'Biology', sourceHint: 'They have nerve nets' },
  { id: 'bio-032', statement: 'The blue whale is the largest animal known to have ever lived.', answer: true, category: 'Biology', sourceHint: 'Body mass' },
  { id: 'bio-033', statement: 'Ants are social insects that live in colonies.', answer: true, category: 'Biology', sourceHint: 'Eusociality' },
  { id: 'bio-034', statement: 'Most of a human body’s cells are red blood cells by count.', answer: true, category: 'Biology', sourceHint: 'Cell counts' },
  { id: 'bio-035', statement: 'Coral is a type of rock, not a living organism.', answer: false, category: 'Biology', sourceHint: 'Corals are animals' },
  { id: 'bio-036', statement: 'Photosynthesis requires sunlight.', answer: true, category: 'Biology', sourceHint: 'Light reactions' },
  { id: 'bio-037', statement: 'Kangaroos are marsupials.', answer: true, category: 'Biology', sourceHint: 'Pouched mammals' },
  { id: 'bio-038', statement: 'The human eye detects sound waves.', answer: false, category: 'Biology', sourceHint: 'It detects light' },
  { id: 'bio-039', statement: 'Most snakes lay eggs.', answer: true, category: 'Biology', sourceHint: 'Oviparous reptiles' },
  { id: 'bio-040', statement: 'Earthworms help aerate soil.', answer: true, category: 'Biology', sourceHint: 'Soil ecology' },

  // ── Mixed difficulty additions ────────────────────────────────────────
  { id: 'mix-001', statement: 'The currency of Japan is the yen.', answer: true, category: 'Everyday', sourceHint: 'Currencies' },
  { id: 'mix-002', statement: 'The currency of the United Kingdom is the euro.', answer: false, category: 'Everyday', sourceHint: 'It is the pound sterling' },
  { id: 'mix-003', statement: 'A “byte” consists of 8 bits.', answer: true, category: 'Science', sourceHint: 'Computing' },
  { id: 'mix-004', statement: 'The binary number system uses only 0s and 1s.', answer: true, category: 'Mathematics', sourceHint: 'Base 2' },
  { id: 'mix-005', statement: 'HTTP stands for HyperText Transfer Protocol.', answer: true, category: 'Science', sourceHint: 'Web protocols' },
  { id: 'mix-006', statement: 'The Mona Lisa is displayed in the Louvre.', answer: true, category: 'History', sourceHint: 'Paris museum' },
  { id: 'mix-007', statement: 'The official language of Brazil is Spanish.', answer: false, category: 'Language', sourceHint: 'It is Portuguese' },
  { id: 'mix-008', statement: 'The Sahara Desert is larger than the contiguous United States.', answer: true, category: 'Geography', sourceHint: 'Area comparison' },
  { id: 'mix-009', statement: 'A right triangle can have two right angles.', answer: false, category: 'Mathematics', sourceHint: 'Angle sum is 180°' },
  { id: 'mix-010', statement: 'The element oxygen is essential for human respiration.', answer: true, category: 'Science', sourceHint: 'Cellular respiration' },
  { id: 'mix-011', statement: 'The Pacific Ocean is larger than all land area on Earth combined.', answer: true, category: 'Geography', sourceHint: 'Pacific ~165M km², land ~149M km²' },
  { id: 'mix-012', statement: 'A standard piano has 88 keys.', answer: true, category: 'Everyday', sourceHint: 'Modern piano' },
  { id: 'mix-013', statement: 'The Great Pyramid was the tallest man-made structure for thousands of years.', answer: true, category: 'History', sourceHint: 'Until the 14th century' },
  { id: 'mix-014', statement: 'Lightning never strikes the same place twice.', answer: false, category: 'Science', sourceHint: 'A myth — it often does' },
  { id: 'mix-015', statement: 'The human brain is fully grown by age two.', answer: false, category: 'Biology', sourceHint: 'It keeps developing into adulthood' },
  { id: 'mix-016', statement: 'Antarctica is the coldest continent.', answer: true, category: 'Geography', sourceHint: 'Lowest recorded temperatures' },
  { id: 'mix-017', statement: 'A compass needle points toward magnetic north.', answer: true, category: 'Science', sourceHint: 'Magnetism' },
  { id: 'mix-018', statement: 'The number of degrees in a full circle is 360.', answer: true, category: 'Mathematics', sourceHint: 'Angles' },
  { id: 'mix-019', statement: 'Sharks are mammals.', answer: false, category: 'Biology', sourceHint: 'They are fish' },
  { id: 'mix-020', statement: 'The Earth’s core is hotter than its surface.', answer: true, category: 'Science', sourceHint: 'Geothermal gradient' },
];
