import type { EstimationFact } from '../types';

// Numeric quantities for 90%-interval estimation. Values are chosen to be stable
// and verifiable (physical constants, geography, well-fixed measurements,
// historical dates). Populations and other fast-decaying figures are avoided.

export const estimationFacts: EstimationFact[] = [
  // ── Physical constants & science ──────────────────────────────────────
  { id: 'est-001', question: 'Speed of light in a vacuum', value: 299792, unit: 'km/s', category: 'Science', sourceHint: 'Physics constant' },
  { id: 'est-002', question: 'Approximate boiling point of water at sea level', value: 100, unit: '°C', category: 'Science', sourceHint: 'Standard pressure' },
  { id: 'est-003', question: 'Number of elements in the periodic table (confirmed)', value: 118, unit: 'elements', category: 'Science', sourceHint: 'Up to oganesson' },
  { id: 'est-004', question: 'Acceleration due to gravity at Earth’s surface', value: 9.81, unit: 'm/s²', category: 'Science', sourceHint: 'Standard gravity' },
  { id: 'est-005', question: 'Number of bones in the adult human body', value: 206, unit: 'bones', category: 'Science', sourceHint: 'Adult skeleton' },
  { id: 'est-006', question: 'Normal human body temperature', value: 37, unit: '°C', category: 'Science', sourceHint: 'Approximate average' },
  { id: 'est-007', question: 'Freezing point of water in Fahrenheit', value: 32, unit: '°F', category: 'Science', sourceHint: 'Fahrenheit scale' },
  { id: 'est-008', question: 'Approximate percentage of nitrogen in Earth’s atmosphere', value: 78, unit: '%', category: 'Science', sourceHint: 'Atmospheric composition' },
  { id: 'est-009', question: 'Approximate percentage of oxygen in Earth’s atmosphere', value: 21, unit: '%', category: 'Science', sourceHint: 'Atmospheric composition' },
  { id: 'est-010', question: 'Number of chambers in the human heart', value: 4, unit: 'chambers', category: 'Science', sourceHint: 'Cardiac anatomy' },
  { id: 'est-011', question: 'Approximate value of pi to two decimals', value: 3.14, unit: '', category: 'Mathematics', sourceHint: 'π' },
  { id: 'est-012', question: 'Number of seconds in one hour', value: 3600, unit: 'seconds', category: 'Mathematics', sourceHint: '60 × 60' },
  { id: 'est-013', question: 'Number of minutes in one day', value: 1440, unit: 'minutes', category: 'Mathematics', sourceHint: '24 × 60' },
  { id: 'est-014', question: 'Approximate absolute zero in Celsius', value: -273, unit: '°C', category: 'Science', sourceHint: '0 kelvin' },
  { id: 'est-015', question: 'Number of teeth in a full adult human set (with wisdom teeth)', value: 32, unit: 'teeth', category: 'Science', sourceHint: 'Dental anatomy' },

  // ── Astronomy ──────────────────────────────────────────────────────────
  { id: 'est-016', question: 'Average distance from the Earth to the Sun', value: 149600000, unit: 'km', category: 'Astronomy', sourceHint: '1 astronomical unit' },
  { id: 'est-017', question: 'Approximate diameter of the Earth', value: 12742, unit: 'km', category: 'Astronomy', sourceHint: 'Mean diameter' },
  { id: 'est-018', question: 'Approximate diameter of the Moon', value: 3474, unit: 'km', category: 'Astronomy', sourceHint: 'Lunar diameter' },
  { id: 'est-019', question: 'Time for sunlight to reach Earth', value: 8.3, unit: 'minutes', category: 'Astronomy', sourceHint: 'Light travel time' },
  { id: 'est-020', question: 'Approximate average distance from Earth to the Moon', value: 384400, unit: 'km', category: 'Astronomy', sourceHint: 'Lunar distance' },
  { id: 'est-021', question: 'Number of planets in the Solar System', value: 8, unit: 'planets', category: 'Astronomy', sourceHint: 'IAU definition' },
  { id: 'est-022', question: 'Approximate orbital period of Halley’s Comet', value: 76, unit: 'years', category: 'Astronomy', sourceHint: 'Comet orbit' },
  { id: 'est-023', question: 'Approximate diameter of the Sun', value: 1392000, unit: 'km', category: 'Astronomy', sourceHint: 'Solar diameter' },
  { id: 'est-024', question: 'Number of days for the Moon to orbit Earth (sidereal)', value: 27, unit: 'days', category: 'Astronomy', sourceHint: 'Lunar month' },
  { id: 'est-025', question: 'Approximate age of the Earth', value: 4540, unit: 'million years', category: 'Astronomy', sourceHint: 'Geological estimate' },

  // ── Geography: mountains, rivers, areas ──────────────────────────────
  { id: 'est-026', question: 'Height of Mount Everest above sea level', value: 8849, unit: 'm', category: 'Geography', sourceHint: 'Highest peak' },
  { id: 'est-027', question: 'Approximate length of the Nile River', value: 6650, unit: 'km', category: 'Geography', sourceHint: 'River length' },
  { id: 'est-028', question: 'Approximate length of the Amazon River', value: 6400, unit: 'km', category: 'Geography', sourceHint: 'River length' },
  { id: 'est-029', question: 'Height of the Eiffel Tower (to tip)', value: 330, unit: 'm', category: 'Geography', sourceHint: 'Paris landmark' },
  { id: 'est-030', question: 'Height of the Burj Khalifa', value: 828, unit: 'm', category: 'Geography', sourceHint: 'Tallest building' },
  { id: 'est-031', question: 'Approximate depth of the Mariana Trench (deepest point)', value: 10935, unit: 'm', category: 'Geography', sourceHint: 'Challenger Deep' },
  { id: 'est-032', question: 'Number of countries in Africa', value: 54, unit: 'countries', category: 'Geography', sourceHint: 'UN members' },
  { id: 'est-033', question: 'Approximate height of Niagara Falls (Horseshoe)', value: 57, unit: 'm', category: 'Geography', sourceHint: 'Waterfall height' },
  { id: 'est-034', question: 'Approximate length of the Great Wall of China (all sections)', value: 21196, unit: 'km', category: 'Geography', sourceHint: 'Surveyed length' },
  { id: 'est-035', question: 'Approximate area of Australia', value: 7692000, unit: 'km²', category: 'Geography', sourceHint: 'Continent/country' },
  { id: 'est-036', question: 'Approximate area of the Sahara Desert', value: 9200000, unit: 'km²', category: 'Geography', sourceHint: 'Largest hot desert' },
  { id: 'est-037', question: 'Approximate maximum depth of Lake Baikal', value: 1642, unit: 'm', category: 'Geography', sourceHint: 'Deepest lake' },
  { id: 'est-038', question: 'Height of the Statue of Liberty (torch to base of pedestal foundation)', value: 93, unit: 'm', category: 'Geography', sourceHint: 'Full height' },
  { id: 'est-039', question: 'Approximate length of the Panama Canal', value: 82, unit: 'km', category: 'Geography', sourceHint: 'Ship canal' },
  { id: 'est-040', question: 'Approximate height of Kilimanjaro', value: 5895, unit: 'm', category: 'Geography', sourceHint: 'Highest African peak' },
  { id: 'est-041', question: 'Number of US states', value: 50, unit: 'states', category: 'Geography', sourceHint: 'United States' },
  { id: 'est-042', question: 'Approximate area of the Pacific Ocean', value: 165000000, unit: 'km²', category: 'Geography', sourceHint: 'Largest ocean' },
  { id: 'est-043', question: 'Approximate length of the Mississippi River', value: 3766, unit: 'km', category: 'Geography', sourceHint: 'River length' },
  { id: 'est-044', question: 'Approximate length of the English Channel at its narrowest', value: 33, unit: 'km', category: 'Geography', sourceHint: 'Strait of Dover' },
  { id: 'est-045', question: 'Approximate area of Greenland', value: 2166000, unit: 'km²', category: 'Geography', sourceHint: 'Largest island' },

  // ── History: dates ────────────────────────────────────────────────────
  { id: 'est-046', question: 'Year the first man walked on the Moon', value: 1969, unit: 'year', category: 'History', sourceHint: 'Apollo 11' },
  { id: 'est-047', question: 'Year World War II ended', value: 1945, unit: 'year', category: 'History', sourceHint: '20th century' },
  { id: 'est-048', question: 'Year the Berlin Wall fell', value: 1989, unit: 'year', category: 'History', sourceHint: 'Cold War' },
  { id: 'est-049', question: 'Year the Titanic sank', value: 1912, unit: 'year', category: 'History', sourceHint: 'Maiden voyage' },
  { id: 'est-050', question: 'Year the United States declared independence', value: 1776, unit: 'year', category: 'History', sourceHint: 'Declaration' },
  { id: 'est-051', question: 'Year the French Revolution began', value: 1789, unit: 'year', category: 'History', sourceHint: 'Bastille' },
  { id: 'est-052', question: 'Year Columbus first reached the Americas', value: 1492, unit: 'year', category: 'History', sourceHint: 'First voyage' },
  { id: 'est-053', question: 'Year the Wright brothers made their first flight', value: 1903, unit: 'year', category: 'History', sourceHint: 'Kitty Hawk' },
  { id: 'est-054', question: 'Year the Eiffel Tower was completed', value: 1889, unit: 'year', category: 'History', sourceHint: 'World’s Fair' },
  { id: 'est-055', question: 'Year the Magna Carta was sealed', value: 1215, unit: 'year', category: 'History', sourceHint: 'England' },
  { id: 'est-056', question: 'Year the first modern Olympic Games were held', value: 1896, unit: 'year', category: 'History', sourceHint: 'Athens' },
  { id: 'est-057', question: 'Year Sputnik 1 was launched', value: 1957, unit: 'year', category: 'History', sourceHint: 'First satellite' },
  { id: 'est-058', question: 'Year the World Wide Web was proposed by Tim Berners-Lee', value: 1989, unit: 'year', category: 'History', sourceHint: 'CERN proposal' },
  { id: 'est-059', question: 'Year Mount Vesuvius destroyed Pompeii', value: 79, unit: 'AD', category: 'History', sourceHint: 'Roman era' },
  { id: 'est-060', question: 'Year the printing press was developed by Gutenberg (approx.)', value: 1440, unit: 'year', category: 'History', sourceHint: 'Movable type' },

  // ── Measurements & everyday ──────────────────────────────────────────
  { id: 'est-061', question: 'Number of keys on a standard piano', value: 88, unit: 'keys', category: 'Everyday', sourceHint: 'Modern piano' },
  { id: 'est-062', question: 'Number of squares on a chessboard', value: 64, unit: 'squares', category: 'Everyday', sourceHint: '8 × 8' },
  { id: 'est-063', question: 'Number of cards in a standard deck (no jokers)', value: 52, unit: 'cards', category: 'Everyday', sourceHint: 'Playing cards' },
  { id: 'est-064', question: 'Number of degrees in a full circle', value: 360, unit: 'degrees', category: 'Mathematics', sourceHint: 'Angles' },
  { id: 'est-065', question: 'Number of letters in the English alphabet', value: 26, unit: 'letters', category: 'Language', sourceHint: 'Latin alphabet' },
  { id: 'est-066', question: 'Number of days in a leap year', value: 366, unit: 'days', category: 'Everyday', sourceHint: 'Calendar' },
  { id: 'est-067', question: 'Number of meters in a mile (approx.)', value: 1609, unit: 'm', category: 'Mathematics', sourceHint: 'Unit conversion' },
  { id: 'est-068', question: 'Number of feet in a meter (approx.)', value: 3.28, unit: 'feet', category: 'Mathematics', sourceHint: 'Unit conversion' },
  { id: 'est-069', question: 'Number of millimeters in one inch', value: 25.4, unit: 'mm', category: 'Mathematics', sourceHint: 'Exact definition' },
  { id: 'est-070', question: 'Number of players on a soccer team on the field (per side)', value: 11, unit: 'players', category: 'Everyday', sourceHint: 'Association football' },
  { id: 'est-071', question: 'Number of players on a basketball team on the court (per side)', value: 5, unit: 'players', category: 'Everyday', sourceHint: 'Basketball' },
  { id: 'est-072', question: 'Standard marathon distance', value: 42.2, unit: 'km', category: 'Everyday', sourceHint: '26.2 miles' },
  { id: 'est-073', question: 'Number of strings on a standard guitar', value: 6, unit: 'strings', category: 'Everyday', sourceHint: 'Acoustic/electric' },
  { id: 'est-074', question: 'Number of bits in a byte', value: 8, unit: 'bits', category: 'Science', sourceHint: 'Computing' },
  { id: 'est-075', question: 'Number of colors in a rainbow (traditional)', value: 7, unit: 'colors', category: 'Everyday', sourceHint: 'ROYGBIV' },
  { id: 'est-076', question: 'Number of holes on a standard golf course', value: 18, unit: 'holes', category: 'Everyday', sourceHint: 'Golf' },
  { id: 'est-077', question: 'Number of sides on a stop sign (octagon)', value: 8, unit: 'sides', category: 'Everyday', sourceHint: 'Road signs' },
  { id: 'est-078', question: 'Number of zeros in one million', value: 6, unit: 'zeros', category: 'Mathematics', sourceHint: 'Place value' },
  { id: 'est-079', question: 'Number of zeros in one billion (short scale)', value: 9, unit: 'zeros', category: 'Mathematics', sourceHint: 'Place value' },
  { id: 'est-080', question: 'Number of hours in a week', value: 168, unit: 'hours', category: 'Mathematics', sourceHint: '7 × 24' },

  // ── More science & nature ─────────────────────────────────────────────
  { id: 'est-081', question: 'Approximate gestation period of a human', value: 280, unit: 'days', category: 'Science', sourceHint: '~40 weeks' },
  { id: 'est-082', question: 'Approximate average adult human resting heart rate', value: 70, unit: 'bpm', category: 'Science', sourceHint: 'Resting rate' },
  { id: 'est-083', question: 'Number of pairs of chromosomes in a human cell', value: 23, unit: 'pairs', category: 'Science', sourceHint: 'Human genome' },
  { id: 'est-084', question: 'Approximate speed of sound in air at room temperature', value: 343, unit: 'm/s', category: 'Science', sourceHint: 'At ~20 °C' },
  { id: 'est-085', question: 'Atomic number of carbon', value: 6, unit: '', category: 'Science', sourceHint: 'Periodic table' },
  { id: 'est-086', question: 'Atomic number of oxygen', value: 8, unit: '', category: 'Science', sourceHint: 'Periodic table' },
  { id: 'est-087', question: 'Approximate percentage of Earth’s surface covered by water', value: 71, unit: '%', category: 'Science', sourceHint: 'Oceans and seas' },
  { id: 'est-088', question: 'Approximate number of hearts an octopus has', value: 3, unit: 'hearts', category: 'Science', sourceHint: 'Cephalopod' },
  { id: 'est-089', question: 'Approximate top speed of a cheetah', value: 110, unit: 'km/h', category: 'Science', sourceHint: 'Fastest land animal' },
  { id: 'est-090', question: 'Approximate length of a blue whale (largest)', value: 30, unit: 'm', category: 'Science', sourceHint: 'Largest animal' },
  { id: 'est-091', question: 'Approximate wingspan record of a wandering albatross', value: 3.5, unit: 'm', category: 'Science', sourceHint: 'Largest wingspan bird' },
  { id: 'est-092', question: 'Approximate lifespan of a giant tortoise (can exceed)', value: 100, unit: 'years', category: 'Science', sourceHint: 'Longevity' },
  { id: 'est-093', question: 'Number of legs on an insect', value: 6, unit: 'legs', category: 'Science', sourceHint: 'Insect anatomy' },
  { id: 'est-094', question: 'Number of legs on a spider', value: 8, unit: 'legs', category: 'Science', sourceHint: 'Arachnid anatomy' },
  { id: 'est-095', question: 'Approximate percentage of human body that is water', value: 60, unit: '%', category: 'Science', sourceHint: 'Adult average' },

  // ── Geography (extended) ──────────────────────────────────────────────
  { id: 'est-096', question: 'Number of time zones Russia spans', value: 11, unit: 'time zones', category: 'Geography', sourceHint: 'Largest country' },
  { id: 'est-097', question: 'Approximate area of the Mediterranean Sea', value: 2500000, unit: 'km²', category: 'Geography', sourceHint: 'Sea area' },
  { id: 'est-098', question: 'Approximate length of the Danube River', value: 2850, unit: 'km', category: 'Geography', sourceHint: 'European river' },
  { id: 'est-099', question: 'Approximate height of Angel Falls (world’s tallest waterfall)', value: 979, unit: 'm', category: 'Geography', sourceHint: 'Venezuela' },
  { id: 'est-100', question: 'Approximate area of the United States', value: 9834000, unit: 'km²', category: 'Geography', sourceHint: 'Total area' },
  { id: 'est-101', question: 'Approximate area of Canada', value: 9985000, unit: 'km²', category: 'Geography', sourceHint: 'Second-largest country' },
  { id: 'est-102', question: 'Approximate area of Russia', value: 17098000, unit: 'km²', category: 'Geography', sourceHint: 'Largest country' },
  { id: 'est-103', question: 'Approximate length of the Trans-Siberian Railway', value: 9289, unit: 'km', category: 'Geography', sourceHint: 'Longest railway' },
  { id: 'est-104', question: 'Approximate elevation of the Dead Sea shore below sea level', value: -430, unit: 'm', category: 'Geography', sourceHint: 'Lowest land' },
  { id: 'est-105', question: 'Number of Great Lakes in North America', value: 5, unit: 'lakes', category: 'Geography', sourceHint: 'HOMES' },

  // ── Math & misc ────────────────────────────────────────────────────────
  { id: 'est-106', question: 'Value of 2 to the 10th power', value: 1024, unit: '', category: 'Mathematics', sourceHint: 'Powers of two' },
  { id: 'est-107', question: 'Sum of the interior angles of a triangle', value: 180, unit: 'degrees', category: 'Mathematics', sourceHint: 'Geometry' },
  { id: 'est-108', question: 'Sum of the interior angles of a quadrilateral', value: 360, unit: 'degrees', category: 'Mathematics', sourceHint: 'Geometry' },
  { id: 'est-109', question: 'Number of prime numbers below 20', value: 8, unit: 'primes', category: 'Mathematics', sourceHint: '2,3,5,7,11,13,17,19' },
  { id: 'est-110', question: 'Value of 12 factorial divided by 11 factorial', value: 12, unit: '', category: 'Mathematics', sourceHint: 'Factorials' },
  { id: 'est-111', question: 'Number of edges on a cube', value: 12, unit: 'edges', category: 'Mathematics', sourceHint: 'Polyhedra' },
  { id: 'est-112', question: 'Number of faces on a standard die', value: 6, unit: 'faces', category: 'Mathematics', sourceHint: 'Cube' },
  { id: 'est-113', question: 'Number of vertices on a cube', value: 8, unit: 'vertices', category: 'Mathematics', sourceHint: 'Polyhedra' },
  { id: 'est-114', question: 'Approximate value of the golden ratio', value: 1.618, unit: '', category: 'Mathematics', sourceHint: 'φ' },
  { id: 'est-115', question: 'Approximate value of the square root of 2', value: 1.414, unit: '', category: 'Mathematics', sourceHint: '√2' },

  // ── Human-scale & everyday ────────────────────────────────────────────
  { id: 'est-116', question: 'Number of seconds in one day', value: 86400, unit: 'seconds', category: 'Mathematics', sourceHint: '24 × 60 × 60' },
  { id: 'est-117', question: 'Number of days in a (non-leap) year', value: 365, unit: 'days', category: 'Everyday', sourceHint: 'Calendar' },
  { id: 'est-118', question: 'Number of weeks in a year (approx.)', value: 52, unit: 'weeks', category: 'Everyday', sourceHint: 'Calendar' },
  { id: 'est-119', question: 'Number of bones a newborn baby has (approx.)', value: 300, unit: 'bones', category: 'Science', sourceHint: 'Some fuse with age' },
  { id: 'est-120', question: 'Approximate number of taste buds on a human tongue', value: 5000, unit: 'taste buds', category: 'Science', sourceHint: 'Order of magnitude' },
  { id: 'est-121', question: 'Approximate length of human DNA in a single cell, uncoiled', value: 2, unit: 'meters', category: 'Science', sourceHint: 'Total DNA length' },
  { id: 'est-122', question: 'Number of permanent UN Security Council members', value: 5, unit: 'members', category: 'History', sourceHint: 'UNSC' },
  { id: 'est-123', question: 'Number of strings on a violin', value: 4, unit: 'strings', category: 'Everyday', sourceHint: 'Orchestral instrument' },
  { id: 'est-124', question: 'Number of players on a baseball team on the field (per side)', value: 9, unit: 'players', category: 'Everyday', sourceHint: 'Baseball' },
  { id: 'est-125', question: 'Number of moons of Mars', value: 2, unit: 'moons', category: 'Astronomy', sourceHint: 'Phobos and Deimos' },
];
